---
- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Enable and configure UFW
  community.general.ufw:
    state: enabled
    default_incoming_policy: deny
    default_outgoing_policy: allow

- name: Allow CapRover ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
    - 3000
