---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Set UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Allow CapRover ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22" # SSH
    - "80" # HTTP
    - "443" # HTTPS
    - "3000" # CapRover UI

- name: Enable UFW
  community.general.ufw:
    state: enabled
