---
all:
  vars:
    ansible_user: caprover_lara
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:
    caprover_servers:
      hosts:
        caprover_server_1:
          ansible_host: 64.227.144.188
        # caprover_server_2:
        #   ansible_host: 64.227.155.199
        # caprover_server_3:
        #   ansible_host: 64.227.166.210
