---
- name: Ensure users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
    create_home: true
  loop: "{{ users }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"

- name: Add authorized SSH keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.key_path) }}"
    state: present
    manage_dir: false
  loop: "{{ users }}"
