---
- name: Install required dependencies
  apt:
    name:
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker

- name: Install Docker Engine and CLI
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker Compose v2 plugin (modern approach)
  apt:
    name: docker-compose-plugin
    state: present

- name: Ensure user is added to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
